version: "3"

services:
  namenode:
    image: zhongruizhi/hadoop-namenode:3.3.6-java8-amd64
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: zhongruizhi/hadoop-datanode:3.3.6-java8-amd64
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
  hive-server:
    image: zhongruizhi/hive:3.1.3-java8-amd64
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: zhongruizhi/hive:3.1.3-java8-amd64
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: zhongruizhi/hive-metastore-postgresql:16.2-amd64
  presto-coordinator:
    image: prestodb/presto:0.285-amd64
    ports:
      - "8080:8080"

volumes:
  namenode:
  datanode:
